[agent]
  interval = "100ms"
  flush_interval = "100ms"

# ── INPUT 1: Telemetría del coche/simulador ─────────────────────────────
[[inputs.mqtt_consumer]]
  servers       = ["tcp://tfg_mosquitto:1883"]
  topics        = ["uex/telemetria/skoda"]
  data_format   = "json"
  name_override = "coche_pruebas"
  json_time_key    = "timestamp"
  json_time_format = "unix_ns"

# ── INPUT 2: Predicciones de los modelos ML ───────────────────────────────────
[[inputs.mqtt_consumer]]
  servers       = ["tcp://tfg_mosquitto:1883"]
  topics        = ["uex/predicciones/skoda"]
  data_format   = "json"
  name_override = "predicciones_ml"
  json_time_key    = "timestamp"
  json_time_format = "unix_ns"

# ── OUTPUT ───────────────────────────────────────────────────────
[[outputs.influxdb_v2]]
  urls         = ["http://tfg_influxdb:8086"]
  token        = "uex-motorsport-token"
  organization = "uex_motorsport"
  bucket       = "telemetria"